import {useRef, useState, type ChangeEvent, type PointerEvent as ReactPointerEvent} from 'react';
import {ArrowDown, ArrowLeft, ArrowUp, Download, Eye, Grip, ImagePlus, LayoutDashboard, PackagePlus, RotateCcw, Save, Settings2, Trash2, Upload} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useContent} from '../context/ContentContext';
import type {Product, SiteContent} from '../types';
import {publicAsset} from '../utils/assets';

const blankProduct: Product = {id:'new-piece', name:'New collection piece', category:'Lighting', season:'All year', space:'Living', image:publicAsset('assets/products/oia.jpg'), note:'Describe where this belongs and what makes it useful.'};

export default function Admin() {
  const {content,setContent,reset,exportContent,importContent}=useContent();
  const [tab,setTab]=useState<'content'|'collection'|'layout'>('content');
  const [notice,setNotice]=useState('All edits save automatically in this browser.');
  const fileRef=useRef<HTMLInputElement>(null);
  const setField=<K extends keyof SiteContent>(key:K,value:SiteContent[K])=>setContent(c=>({...c,[key]:value}));
  const uploadImage=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>setField('heroImage',String(reader.result)); reader.readAsDataURL(file)};
  const importJson=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0]; if(!file)return; try{await importContent(file);setNotice('Content file imported successfully.')}catch(e){setNotice(e instanceof Error?e.message:'Import failed.')}};
  const moveProduct=(index:number,direction:-1|1)=>setContent(c=>{const items=[...c.products];const next=index+direction;if(next<0||next>=items.length)return c;[items[index],items[next]]=[items[next],items[index]];return {...c,products:items}});
  const updateProduct=(id:string,key:keyof Product,value:string)=>setContent(c=>({...c,products:c.products.map(p=>p.id===id?{...p,[key]:value}:p)}));
  const pointerDown=(e:ReactPointerEvent<HTMLDivElement>)=>{const target=e.currentTarget;target.setPointerCapture(e.pointerId);const rect=target.parentElement!.getBoundingClientRect();const move=(ev:globalThis.PointerEvent)=>setField('heroObject',{x:Math.max(0,Math.min(100,(ev.clientX-rect.left)/rect.width*100)),y:Math.max(0,Math.min(100,(ev.clientY-rect.top)/rect.height*100))});const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};

  return <div className="admin-shell">
    <aside className="admin-sidebar"><Link className="admin-brand" to="/"><span>NK</span><div><b>Content studio</b><small>Live site controls</small></div></Link><nav><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}><LayoutDashboard/>Brand & copy</button><button className={tab==='collection'?'active':''} onClick={()=>setTab('collection')}><PackagePlus/>Collection</button><button className={tab==='layout'?'active':''} onClick={()=>setTab('layout')}><Grip/>Layout lab</button></nav><div className="admin-side-bottom"><Link to="/"><Eye/>View live website</Link><button onClick={reset}><RotateCcw/>Restore published copy</button></div></aside>
    <main className="admin-main"><header><div><span>NK / STUDIO</span><h1>{tab==='content'?'Brand & copy':tab==='collection'?'Collection manager':'Layout lab'}</h1></div><div className="admin-actions"><button onClick={()=>fileRef.current?.click()}><Upload/>Import</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={importJson}/><button onClick={exportContent}><Download/>Export</button><Link to="/"><ArrowLeft/>Exit studio</Link></div></header><p className="admin-notice"><Save/>{notice}</p>
      {tab==='content'&&<div className="admin-grid"><section className="admin-panel"><div className="panel-title"><span>01</span><div><h2>Hero message</h2><p>The first words visitors see.</p></div></div><label>Eyebrow<input value={content.eyebrow} onChange={e=>setField('eyebrow',e.target.value)}/></label><label>Headline, line one<input value={content.heroTitle} onChange={e=>setField('heroTitle',e.target.value)}/></label><label>Headline, accent<input value={content.heroAccent} onChange={e=>setField('heroAccent',e.target.value)}/></label><label>Introduction<textarea rows={4} value={content.heroBody} onChange={e=>setField('heroBody',e.target.value)}/></label></section><section className="admin-panel"><div className="panel-title"><span>02</span><div><h2>Story & contact</h2><p>Core brand language across the site.</p></div></div><label>Story heading<input value={content.aboutTitle} onChange={e=>setField('aboutTitle',e.target.value)}/></label><label>Story paragraph<textarea rows={5} value={content.aboutBody} onChange={e=>setField('aboutBody',e.target.value)}/></label><label>Contact introduction<textarea rows={3} value={content.contactNote} onChange={e=>setField('contactNote',e.target.value)}/></label></section><section className="admin-panel media-panel"><div className="panel-title"><span>03</span><div><h2>Hero media</h2><p>Upload from your device or use a direct image path.</p></div></div><div className="admin-image"><img src={content.heroImage} alt="Current hero"/></div><label className="upload-button"><ImagePlus/>Choose image<input hidden type="file" accept="image/*" onChange={uploadImage}/></label><label>Image path<input value={content.heroImage} onChange={e=>setField('heroImage',e.target.value)}/></label></section></div>}
      {tab==='collection'&&<div className="collection-admin"><div className="collection-toolbar"><p><b>{content.products.length} products</b><span>Reorder, edit, remove or add items. Changes appear live in Explore.</span></p><button onClick={()=>setContent(c=>({...c,products:[...c.products,{...blankProduct,id:`piece-${Date.now()}`}]}))}><PackagePlus/>Add product</button></div>{content.products.map((p,i)=><article className="product-admin-row" key={p.id}><img src={p.image} alt=""/><div className="product-admin-fields"><input aria-label="Product name" value={p.name} onChange={e=>updateProduct(p.id,'name',e.target.value)}/><input aria-label="Product description" value={p.note} onChange={e=>updateProduct(p.id,'note',e.target.value)}/><input aria-label="Product image path" value={p.image} onChange={e=>updateProduct(p.id,'image',e.target.value)}/><div><select aria-label="Product category" value={p.category} onChange={e=>updateProduct(p.id,'category',e.target.value)}>{['Lighting','Coffee','Kitchen','Cooling','Cleaning'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Product season" value={p.season} onChange={e=>updateProduct(p.id,'season',e.target.value)}>{['All year','Summer','Winter','Christmas'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Product space" value={p.space} onChange={e=>updateProduct(p.id,'space',e.target.value)}>{['Living','Kitchen','Outdoor','Bedroom','Workspace'].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="row-actions"><button disabled={i===0} onClick={()=>moveProduct(i,-1)} aria-label="Move up"><ArrowUp/></button><button disabled={i===content.products.length-1} onClick={()=>moveProduct(i,1)} aria-label="Move down"><ArrowDown/></button><button onClick={()=>setContent(c=>({...c,products:c.products.filter(x=>x.id!==p.id)}))} aria-label="Remove product"><Trash2/></button></div></article>)}</div>}
      {tab==='layout'&&<div className="layout-lab"><section><div className="panel-title"><span>01</span><div><h2>Move the signal marker</h2><p>Drag the marker directly across the live hero. Its position is saved.</p></div></div><div className="layout-stage"><img src={content.heroImage} alt="Hero layout preview"/><div className="draggable-object" onPointerDown={pointerDown} style={{left:`${content.heroObject.x}%`,top:`${content.heroObject.y}%`}}><Grip/><span>Signal / 01</span></div></div><div className="position-readout"><span>X {Math.round(content.heroObject.x)}%</span><span>Y {Math.round(content.heroObject.y)}%</span></div></section><aside><Settings2/><h2>Layout guardrails</h2><p>The marker stays inside the safe frame so it cannot overlap the navigation or crop outside the image on smaller screens.</p><ul><li>Percentage-based positioning</li><li>Pointer and touch compatible</li><li>Saved instantly</li><li>Responsive safe zone</li></ul></aside></div>}
    </main>
  </div>;
}
